---
layout:     post   				    # 使用的布局（不需要改）
title:      Promise对象				# 标题 
subtitle:      #副标题
date:       2019-5-14				# 时间
author:     liangping 						# 作者
header-img: img/post-bg-js-version.jpg 	#这篇文章标题背景图片
catalog: true 						# 是否归档
tags:								#标签
    - JavaScript
    - ES6
---

# Promise对象

## Promise对象的含义

promise对象是一个容器，里面保存着未来才会结束的事件（通常是一个一步操作）的结果（可以不是异步事件，promise.try方法）

它有三种状态Pending、Fulfilled、Rejected。一旦promise对象变为fulfilled或者rejected那么它将不能再该改变，一直保持这个结果，这时就称为Resolved（已定型）。**就算改变已经发生，再对Promise对象添加回调函数，也会立即获得到这个结果。这与事件（Event）完全不同**

Promise对象可以避免层层嵌套，将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。
缺点在于：
1. 无法取消Promise，一旦新建它就会立即执行，无法中途取消。
2. 如果不设置回调函数，Promise内部抛出的错误不会反映到外部（Node又一个unhandleedRejection事件，可以监听未捕获的reject错误）
3. 处于Pending状态时，无法得知目前处于哪一个状态（刚刚开始还是即将完成）
   
## Promise构造函数

接受一个函数作为参数，该函数有两个参数`(resolve,reject)`，其中两个参数由JavaScript引擎提供。resolve的作用为，异步操作成功时，将操作的结果作为参数传出；reject的作用为，异步操作失败时，将操作失败的错误传出。

Promise对象生成后，可以使用then方法分别指定Resolved状态和Rejected状态的回调函数。

```javascript
    promise.then(function(value){
        // success
    },function(error){
        //failure
    })
```

then接受两个回调函数作为参数，第一个回调函数时promise对象状态变为resolved时调用，第二个回调函数时promise对象状态变为rejected时调用。其中第二个参数是可选的不一定要提供。这两个函数都接受Promised对象传出的值作为参数。

**Promise新建后会立即执行！！！！！！！！！！！！！**

```javascript
    let promise = new Promise((resolve,reject)=>{
        console.log('first')
    })

    promise.then(()=>{
        console.log('third')
    })

    console.log('second')

    // first
    // second
    // third
```

上述代码，Promise新建后会立即执行，所以首先输出的是first。然后运行到文件末尾，执行输出second。然后then方法执行的回调函数将在当前脚本执行完成后才会执行，所以third最后输出。


## resolve与reject

reject函数通常返回一个Error对象的实例。

```javascript
    reject(nre Error('错误信息'))
```

resolve函数的参数除了正擦会给你的值外，还可能是另一个Promise实例。

```javascript
    let p1 = new Promise((resolve,reject)=>{
        // 。。。
    })

    let p2 = new Promise((resolve,reject)=>{
        // 。。。
        resolve(p1)
    })
```

上面的代码中，p1和p2都是promise的实例，p2的resolve方法将p1作为参数，即一个异步操作的结果是返回另一个异步操作。**此时p1的状态决定了p2的状态，**如果p1的状态为Pending，那么p2的回调函数就会等待p1的状态改变；如果p1的状态已经是Resolved或者Rejected，那么p2的回调函数就会立即执行。

```javascript
    let p1 = new Promise((resolve,reject)=>{
        setTimeout(()=>reject(new Error('fail')),3000)
    })

    let p2 = new Promise((resolve,reject)=>{
        setTimeout(()=>resolve(p1),1000)
    })

    p2
    .then(result => console.log(result))
    .catch(error => console.log(error))

    // Error: fail
```

上述代码中，p1是一个Promise，3秒之后变为rejected。p2的状态在1秒之后改变吗，resolved方法返回的是怕。由于p2返回的是另一个promise，导致p2的状态无效，由p1的状态决定p2的转台。所以后面的then豫剧都是针对后者p1的。再过2秒，p1变为rejected，出发catch方法制定的回调函数。

一般来说，调用resolve或者rejected，promise的使命就完成了，后继操作应该都放到then方法中。所以最后在他们前面加上return语句。

```javascript
    new Promise((resolve,reject)=>{
        return resolve(1)
        //后面的语句不会执行
        console.log(2)
    })
```

## Promise.prototype.then()

Promise实例具有then方法，即then方法是定义在原型对象Promise.prototype上的。它的作用是为Promise实例添加状态改变时的回调函数。

then方法返回的是一个新的promise实例（不是原来那个）。因此可以采用链式的写法，即then后面调用另外一个then方法。

```javascript
    getJSON("/posts.json")
    .then(json => json.post)
    .then(post=>{
        // ...
    },
    error=>{
        // 不包括当前then发生错误的捕获
    })
```

## Promise.prototype.catch()

Promise.prototype.catch()方法是.then(null,rejection)的别名，用于指定发生错误时的回调函数。

```javascript
    getJSON("/posts.json")
    .then(json => json.post)
    .catch(error => {
        // 处理getJSON和前一个then回调函数运行时发生的错误
        console.log(error)
    })
```

**一般来说不适用then的第二个回调函数，而应当使用catch方法处理错误**原因在于catch可以捕获then的错误；更接近try-catch的写法。

**与传统的try-catch代码块不同的是，若果没有使用catch方法制定错误处理回调函数。Promise对象抛出的错误不会传递到外层代码，即不会有任何反应**

Node有一个unhandledRejection事件，专门监听未捕获的reject错误。

```javascript
    process.on('unhandledRejection',function(err,p){
        console.error(err.stack)
    })
```

上面代码中unhandledRejection事件监听函数有两个参数，第一个是错误对象，第二个是报错的Promise实例，可用于了解发生错误的环境信息。

catch方法返回的还是一个promise对象，因此可以接着调用catch、then等方法。


## Promise.all()

Promise.all()方法用于将多个Promise实例包装成一个新的Promise实例。
`let p = Promise.all([p1,p2,p3])`
上面的代码中，Promise.all方法接受一个数组作为参数，其成员都为Promise对象，如果不是将调用Promise.resolve()方法将成员转化为Promise实例。Promise.all方法的参数不一定维数组，但必须具有Iterator接口，且返回的每个成员都是Promise实例

p的状态由p1,p2,p3共同决定，有两种情况：

1. 只有p1，p2，p3的状态都变为Fulfilled，p的状态才会变为Fulfilled，此时p1，p2，p3的返回值组成一个数组，传递给p的回调函数。
2. 只要p1，p2，p3有一个被rejected，p的状态就会变为rejected。此时第一个被rejected的实例的返回值会传递给p的回调函数

```javascript
    let p = Promise.all([2,3,5,7,11,13].map(id=>{
        return getJSON('/post/' + id + '.json')
    }))

    Promise.all(p).then(posts=>{
        // ...
    }).catch(reason => {
        // ...
    })
```

```javascript
    const databasePromise = connectDatabase()

    const bookPromise = databasePromise.then(findAllBooks)

    const userPromise = databasePromise.then(getCurrentUser)

    Promise.all([
        bookPromise,
        userPromise
    ])
    .then(([books,user]) => pickTopRecommentations(books,user))
```

上面的代码中，bookPromise和userPromise是两个异步操作，只有他们的结果都返回，才会触发pickTopRecommentations回调函数。

如果作为参数数组成员的Promise对象本身有catch方法，那么它被reject时不会触发Promise.all()的catch方法。

## Promise.race()

`let p = Promise.race([p1,p2,p3])`

只要p1,p2,p3中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的Promise实例的返回值就会传递给p的回调函数。

## Promise.resolve()

将一个参数转化为Promise对象实例

* 参数是一个Promise对象，原封不动返回该Promise实例
* 参数是一个thenable对象
    
    > thenable对象指具有then方法的对象，比如下面这个对象。
    ```javascript
        let thenable = {
            then:(resolve,reject){
                resolve(42)
            }
        }
    ```

    Promise.resolve方法会将这个对象转化为Promise对象，然后立即执行thenable对象的then方法。

* 参数不是具有then方法的对象或者根本不是对象
  返回Promise实例的状态从生成起就是resolved，所以回调函数会立即执行。Promise.resolve()的参数也会传递给回调函数。

* 不带任何参数，直接返回一个resolved状态的Promise对象实例
  **需要注意的是，立即resolve的Promise对象是在本轮“事件循环”结束时而不是在下一轮“事件循环”开始时执行**

  ```javascript
    setTimeout(() => {
        console.log('three')
    })

    Promise.resolve().then(()=>{
        console.log('two')
    })

    console.log('one')

    // one 
    // two 
    // three
  ```

## Promise.reject()

  Promise.reject(resson)返回一个新的Promise实例，状态为Rejected，不论参数为什么都传递给回调函数